import type { Metadata } from 'next';
import { Petit_Formal_Script } from 'next/font/google';
import '../styles/globals.scss';
import { NextIntlClientProvider, useMessages } from 'next-intl';

const petitFormal = Petit_Formal_Script({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className={petitFormal.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
