import type { Metadata } from 'next';
import '../styles/globals.scss';
import { NextIntlClientProvider } from 'next-intl';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { getMessages } from 'next-intl/server';
import { getServerSession } from 'next-auth';

import SessionProvider from './SessionProvider';
config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Kriszti & Dani',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  const session = await getServerSession();
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AppRouterCacheProvider>
            <SessionProvider session={session}>
              {children}
            </SessionProvider>
          </AppRouterCacheProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
